"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = "$directory$all"

[buf]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
truncation_length = 18
only_attached = true

[git_status]
disabled = true

[golang]
symbol = " "

[nodejs]
style = "green"